config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'

   root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<%= render '/partials/carousel' %>
<!-- Page Content -->
    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Welcome to Armstrong Marine
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>Strength & Durability</h4>
                    </div>
                    <div class="panel-body">
                        <p>High impact marine-grade alloy aluminum stronger and lighter than conventional fiberglass boats.                   </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Handcrafted Excellence</h4>
                    </div>
                    <div class="panel-body">
                        <p>Constructed with precise attention to detail by certified welders and craftsmen.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i>Unique Construction</h4>
                    </div>
                    <div class="panel-body">
                        <p>"Suspended Framing" construction eliminates metal fatigue and the inevitable cracking that follows.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Recent Launches</h2>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <%= image_tag("lander_700x450.jpg", alt: "Bow Lander", :width => 360, :height => 230) %>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <%= image_tag("fire_700x450.jpg", alt: "Bow Lander", :width => 360, :height => 230) %>
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
            <div class="col-md-4 col-sm-6">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-portfolio img-hover" src="http://placehold.it/700x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Features Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Modern Business Features</h2>
            </div>
            <div class="col-md-6">
                <p>The Modern Business template by Start Bootstrap includes:</p>
                <ul>
                    <li><strong>Bootstrap v3.2.0</strong>
                    </li>
                    <li>jQuery v1.11.0</li>
                    <li>Font Awesome v4.1.0</li>
                    <li>Working PHP contact form with validation</li>
                    <li>Unstyled page elements for easy customization</li>
                    <li>17 HTML pages</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
            </div>
            <div class="col-md-6">
                <img class="img-responsive" src="http://placehold.it/700x450" alt="">
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Section -->
        <div class="well">
            <div class="row">
                <div class="col-md-8">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
                </div>
            </div>
        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Armstrong Marine, Inc.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render 'partials/nav' %>

<%= yield %>
</div>
</body>
</html>

app/views/partials/_carousel.html.erb
<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <%= image_tag("Storm.png", alt: "Storm", :width => 1631, :height => 629) %>
            
            <div class="carousel-caption">
                <h2>The Storm</h2>
                <p> The Storm is the finest example of a twenty-first century combat boat</p>
            </div>
        </div>
        <div class="item">
            <%= image_tag("bow_lander.jpg", alt: "Bow Lander", :width => 1631, :height => 629) %>
             <div class="carousel-caption">
                <h2>Water Taxi</h2>
                <p>Front loading ramp for comfort and ease of access of your passengers</p>
            </div>            
        </div>
        <div class="item">
            <%= image_tag("pilot_boat.jpg", alt: "Pilot Boat", :width => 1631, :height => 629) %>
            <div class="carousel-caption">
                <h2>Pilot Boats</h2>
                <p>Specifically tailored for safe pilot operations</p>
            </div> 
        </div>
        <div class="item">
            <%= image_tag("ams_exc.jpg", alt: "AMS", :width => 1631, :height => 629) %>
            <div class="carousel-caption">
                <h2>Transportation</h2>
                <p>Performance to meet the rigorous demands of the sea</p>
            </div> 
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>

app/views/partials/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Armstrong Marine, Inc.</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">Boat Selector</a>
                </li>
                <li>
                    <a href="<%= home_about_path %>">About Us</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Boats <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Patrol Boats</a>
                        </li>
                        <li>
                            <a href="#">Passenger Vessels</a>
                        </li>
                        <li>
                            <a href="#">Survey boats</a>
                        </li>
                        <li>
                            <a href="#">Dive Boats</a>
                        </li>
                        <li>
                            <a href="#">Fire Boats</a>
                        </li>
                        <li>
                            <a href="#">Pilot Boats</a>
                        </li>
                        <li>
                            <a href="#">Fishing Boats</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Pre-Owned</a>
                </li>
                <li>
                    <a href="#">Jobs</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>